version: '3.4'

services:
  pastebin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  postgres:
    ports:
      - "5432:5432"
    volumes:
      - //c/Program Files/PostgreSQL/16/data
  redis:
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/root/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
