apiVersion: apps/v1
kind: Deployment
metadata:
  name: pastebin-deployment
  labels:
    app: pastebin
spec:
  replicas: 0
  selector:
    matchLabels:
      app: pastebin
  template:
    metadata:
      name: pastebin
      labels:
        app: pastebin
    spec:
      containers:
        - name: pastebin
          image: "pastebin:1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      restartPolicy: Always
      