# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  pastebin:
    build:
      context: "F:\\Rider projects\\Pastebin"
      dockerfile: "Pastebin/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "pastebin:dev"
    ports:
    - "127.0.0.1:57000:57100"
    - "127.0.0.1:57200:57300"
    volumes:
    - "C:\\Users\\danyk\\AppData\\Roaming\\Microsoft\\UserSecrets:/root/.microsoft/usersecrets"
    - "C:\\Users\\danyk\\.nuget\\packages:/root/.nuget/packages"
    - "F:\\Rider projects\\Pastebin\\Pastebin:/app:rw"
    - "F:\\Rider projects\\Pastebin:/src:rw"
    - "C:\\Users\\danyk\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.2\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\danyk\\AppData\\Local\\Programs\\Rider\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\danyk\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_1_14_11_12_42:/var/opt/rider-debugger:rw"
    working_dir: "/app"
